# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  run-analysis:
    docker:
      - image: ghpalmer/staticanalysis
    steps:
      - checkout
      - run:
          name: Run Static Analysis
          command: |
            ./build/static-analysis/run-analysis.sh
  build:
    docker:
      - image: salesforce/salesforcedx:7.59.0-full
    steps:
      - checkout
      - run:
          name: Build and Run Tests
          command: |
            ./build/sfdx/login.sh -l https://login.salesforce.com -c $SFDC_CLIENT_ID -u $SFDC_USER
            ./build/sfdx/run-tests.sh
      - store_test_results:
          path: test-results
  package:
    docker:
      - image: salesforce/salesforcedx:7.59.0-full
    steps:
      - checkout
      - run:
          name: Create Package
          command: |
            ./build/sfdx/login.sh -l https://login.salesforce.com -c $SFDC_CLIENT_ID -u $SFDC_USER
            sfdx force:package:version:create --path force-app --installationkeybypass --wait 10
            packageIdLine=$(grep condition-interpreter@ sfdx-project.json | tail -1)
            idStartingPosition=$((${#packageIdLine}-19))
            packageId=${packageIdLine:$idStartingPosition:18}
            sed -i "s/p0=.*/p0=${packageId})/" README.md
            sed -i "s/--package .*/--package ${packageId}\`/" README.md
            git add sfdx-project.json
            git add README.md
            git config --global user.email "gavinhughpalmer@gmail.com"
            git config --global user.name "Gavin Palmer"
            git commit -m "[skip ci] Updating unlocked package version"
            git push

workflows:
  version: 2
  build_and_test:
    jobs:
      - run-analysis:
            filters:
              branches:
                ignore:
                  - master
      - build:
            requires:
              - run-analysis
            filters:
              branches:
                ignore:
                  - master
  package:
    jobs:
      - package:
            filters:
              branches:
                only:
                  - master
